server:
  port: 8081

# To See H2 Console in Browser:
# http://localhost?8091?h2-console
# Enabling H2 Console

spring:
  h2:
    console:
      enable: true
  # =========================
  # DB
  # =========================
  datasource:
    # url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # driverClassName: org.h2.Driver
    # platforms: h2
    # username: sa
    # password:
    url: jdbc:sqlserver://localhost;databaseName=productDB
    username: fabian
    password: fabian95
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # ==============================
  # JPA / HIBERNATE
  # ==============================

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update
    # database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5P} %m%n"